export function latinToGla(text: string): string {
    return text
        .replace(/Lj/g, 'Ⰾⱐ').replace(/lj/g, 'ⰾⱐ')
        .replace(/Nj/g, 'Ⱀⱐ').replace(/nj/g, 'ⱃⱐ')
        .replace(/A/g, 'Ⰰ').replace(/a/g, 'ⰰ')
        .replace(/B/g, 'Ⰱ').replace(/b/g, 'ⰱ')
        .replace(/C/g, 'Ⱌ').replace(/c/g, 'ⱌ')
        .replace(/Č/g, 'Ⱍ').replace(/č/g, 'ⱍ')
        .replace(/D/g, 'Ⰴ').replace(/d/g, 'ⰴ')
        .replace(/E/g, 'Ⰵ').replace(/e/g, 'ⰵ')
        .replace(/Ě/g, 'Ⱑ') .replace(/ě/g, 'ⱑ')
        .replace(/F/g, 'Ⱇ').replace(/f/g, 'ⱇ')
        .replace(/G/g, 'Ⰳ').replace(/g/g, 'ⰳ')
        .replace(/H/g, 'Ⱈ').replace(/h/g, 'ⱈ')
        .replace(/I/g, 'Ⰻ').replace(/i/g, 'ⰻ')
        .replace(/J/g, 'ⰺ').replace(/j/g, 'ⰺ')
        .replace(/K/g, 'Ⰽ').replace(/k/g, 'ⰽ')
        .replace(/L/g, 'Ⰾ').replace(/l/g, 'ⰾ')
        .replace(/M/g, 'Ⰿ').replace(/m/g, 'ⰿ')
        .replace(/N/g, 'Ⱀ').replace(/n/g, 'ⱀ')
        .replace(/O/g, 'Ⱁ').replace(/o/g, 'ⱁ')
        .replace(/P/g, 'Ⱂ').replace(/p/g, 'ⱂ')
        .replace(/R/g, 'Ⱃ').replace(/r/g, 'ⱃ')
        .replace(/S/g, 'Ⱄ').replace(/s/g, 'ⱄ')
        .replace(/Š/g, 'Ⱎ').replace(/š/g, 'ⱎ')
        .replace(/T/g, 'Ⱅ').replace(/t/g, 'ⱅ')
        .replace(/U/g, 'Ⱆ').replace(/u/g, 'ⱆ')
        .replace(/V/g, 'Ⰲ').replace(/v/g, 'ⰲ')
        .replace(/Y/g, 'Ⱛ').replace(/y/g, 'ⱛ')
        .replace(/Z/g, 'Ⰸ').replace(/z/g, 'ⰸ')
        .replace(/Ž/g, 'Ⰶ').replace(/ž/g, 'ⰶ')
        .replace(/Ę/g, 'Ⱔ').replace(/ę/g, 'ⱔ')
        .replace(/Ų/g, 'Ⱘ').replace(/ų/g, 'ⱘ')
        .replace(/Å/g, 'Ⱝ').replace(/å/g, 'ⱝ')
        .replace(/Ò/g, 'Ⱏ').replace(/ò/g, 'ⱏ')
        .replace(/Ć/g, 'Ⱋ').replace(/ć/g, 'ⱋ')
        .replace(/Đ/g, 'Ⰼ').replace(/đ/g, 'ⰼ')
        .replace(/Ĺ/g, 'Ⰾⱐ').replace(/ĺ/g, 'ⰾⱐ')
        .replace(/Ń/g, 'Ⱀⱐ').replace(/ń/g, 'ⱀⱐ')
        .replace(/Ŕ/g, 'Ⱃⱐ').replace(/ŕ/g, 'ⱃⱐ')
        .replace(/T́/g, 'Ⱅⱐ').replace(/t́/g, 'ⱅⱐ')
        .replace(/D́/g, 'Ⰴⱐ').replace(/d́/g, 'ⰴⱐ')
        .replace(/Ś/g, 'Ⱄⱐ').replace(/ś/g, 'ⱄⱐ')
        .replace(/Ź/g, 'Ⰸⱐ').replace(/ź/g, 'ⰸⱐ')
        ;
}
