name: Create release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version (e.g., 1.21.1)"
        required: true
      description:
        description: "Description of release"
        required: false
jobs:
  update-version:
    name: Update version in package.json
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Update package.json version
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json package-lock.json
          git commit -m "Update version to ${{ inputs.version }}"
          git push origin master

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: update-version
    steps:
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ inputs.version }}
          name: "v${{ inputs.version }}"
          body: "${{ inputs.description }}"
          draft: false
          prerelease: false
