name: PR merged/closed

on:
  pull_request:
    types: [closed]

jobs:
  remove-deploys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove deployments from Cloudflare Pages
        env:
          CF_AUTH_TOKEN: ${{ secrets.CF_AUTH_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_PROJECT_NAME: ${{ secrets.CF_PROJECT_NAME }}
        run: |
          BRANCH_NAME="pr-${{ github.event.number }}"
          echo "Removing deployments for branch: $BRANCH_NAME"

          DEPLOYS=$(curl -s -X GET \
            "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/pages/projects/$CF_PROJECT_NAME/deployments?env=preview" \
            -H "Authorization: Bearer $CF_AUTH_TOKEN" \
            | jq -r '.result[] | select(..deployment_trigger.metadata.branch == "'$BRANCH_NAME'") | .id')

          if [ -z "$DEPLOYS" ]; then
            echo "No deployments found for branch: $BRANCH_NAME"
            exit 0
          fi

          for DEPLOY_ID in $DEPLOYS; do
            echo "Deleting deployment: $DEPLOY_ID"
            curl -s -X DELETE \
              "https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID/pages/projects/$CF_PROJECT_NAME/deployments/$DEPLOY_ID?force=true" \
              -H "Authorization: Bearer $CF_AUTH_TOKEN"
          done
