name: PR merged/closed

on:
  pull_request:
    types: [closed]

jobs:
  remove-deploys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Remove deployments from Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_AUTH_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "Removing deployments for branch: $BRANCH_NAME"

          DEPLOYS=$(curl -s -X GET \
            "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/deployments" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            | jq -r '.result[] | select(.branch == "'$BRANCH_NAME'") | .id')

          if [ -z "$DEPLOYS" ]; then
            echo "No deployments found for branch: $BRANCH_NAME"
            exit 0
          fi

          for DEPLOY_ID in $DEPLOYS; do
            echo "Deleting deployment: $DEPLOY_ID"
            curl -s -X DELETE \
              "https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/deployments/$DEPLOY_ID" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN"
          done
